import { createSurvivalTaskRuntimeFactories } from "./useSurvivalTaskRuntimeFactories.js";
import { createSurvivalTaskRuntimeHandlers } from "./useSurvivalTaskRuntimeHandlers.js";
import { createSurvivalTaskRuntimeLoop } from "./useSurvivalTaskRuntimeLoop.js";

export function createSurvivalTaskRuntime({
  now,
  playerActor,
  placedStructures,
  storageContainer,
  storagePoint,
  craftQueue,
  gatherQueue,
  constructionQueue,
  constructionSites,
  fieldNodes,
  addLog,
  itemName,
  recipeById,
  villagerName,
  actorById,
  fieldNodeById,
  isFieldNodeVisible,
  fieldNodeIndexById,
  actorWorkPoint,
  spawnDroppedLogs,
  spawnDroppedItems,
  nodeWorkPoint,
  storageWorkPoint,
  distanceBetween,
  actorInventoryCount,
  gatherActionById,
  findGatherTargetNode,
  removeItemFromStore,
  consumeActorResources,
  restartVillagerTask,
  respawnFieldNodes,
  checkStockRules,
  checkConstructionSites,
  moveActorForTask,
  actorInteractionDistance,
  buildingById,
  storageInteractionDistance,
  removeTaskFromActiveState,
  scheduleActorTask,
  makeId,
  itemDefinitions,
  t,
}) {
  const {
    createGatherTaskFromTemplate,
    dropOutputsAtActor,
    enqueueMoveThenTask,
    enqueueStorageTransfers,
    refreshMovingDestination,
  } = createSurvivalTaskRuntimeFactories({
    now,
    storagePoint,
    itemName,
    actorById,
    spawnDroppedItems,
    storageWorkPoint,
    actorWorkPoint,
    distanceBetween,
    storageInteractionDistance,
    actorInteractionDistance,
    scheduleActorTask,
    makeId,
    buildingById,
    t,
  });

  const {
    completeConstructionTask,
    completeCraftTask,
    completeEatTask,
    completeGatherTask,
    completeTransferTask,
    depositVillagerOutputs,
    dropVillagerOutputsToField,
    finishTaskWork,
    validateTaskStart,
  } = createSurvivalTaskRuntimeHandlers({
    now,
    playerActor,
    placedStructures,
    storageContainer,
    constructionSites,
    fieldNodes,
    addLog,
    itemName,
    recipeById,
    villagerName,
    actorById,
    fieldNodeById,
    isFieldNodeVisible,
    fieldNodeIndexById,
    spawnDroppedLogs,
    nodeWorkPoint,
    actorInventoryCount,
    gatherActionById,
    findGatherTargetNode,
    removeItemFromStore,
    consumeActorResources,
    restartVillagerTask,
    buildingById,
    removeTaskFromActiveState,
    createGatherTaskFromTemplate,
    dropOutputsAtActor,
    enqueueMoveThenTask,
    enqueueStorageTransfers,
    itemDefinitions,
    t,
  });

  const {
    processMovingTask,
    processWorkingTask,
    remainingSeconds,
    taskProgress,
    tick,
  } = createSurvivalTaskRuntimeLoop({
    now,
    gatherQueue,
    craftQueue,
    constructionQueue,
    actorById,
    distanceBetween,
    moveActorForTask,
    refreshMovingDestination,
    removeTaskFromActiveState,
    completeConstructionTask,
    completeCraftTask,
    completeEatTask,
    completeGatherTask,
    completeTransferTask,
    finishTaskWork,
    validateTaskStart,
    respawnFieldNodes,
    checkStockRules,
    checkConstructionSites,
  });

  return {
    completeConstructionTask,
    completeCraftTask,
    completeEatTask,
    completeGatherTask,
    completeTransferTask,
    depositVillagerOutputs,
    dropVillagerOutputsToField,
    finishTaskWork,
    processMovingTask,
    processWorkingTask,
    remainingSeconds,
    taskProgress,
    tick,
  };
}
